#ifndef _SOCKETERROR_H
#define _SOCKETERROR_H

#include "_Types.h"

/// <summary>
///     Error codes returned by socket operations.
/// </summary>
typedef enum _SocketError
{
    _SOCKET_ERROR_SUCCESS = 0,
    _SOCKET_ERROR_SOCKET_ERROR = -1,
    _SOCKET_ERROR_INTERRUPTED = 10004,
    _SOCKET_ERROR_ACCESS_DENIED = 10013,
    _SOCKET_ERROR_FAULT = 10014,
    _SOCKET_ERROR_INVALID_ARGUMENT = 10022,
    _SOCKET_ERROR_TOO_MANY_OPEN_SOCKETS = 10024,
    _SOCKET_ERROR_WOULD_BLOCK = 10035,
    _SOCKET_ERROR_IN_PROGRESS = 10036,
    _SOCKET_ERROR_ALREADY_IN_PROGRESS = 10037,
    _SOCKET_ERROR_NOT_SOCKET = 10038,
    _SOCKET_ERROR_DESTINATION_ADDRESS_REQUIRED = 10039,
    _SOCKET_ERROR_MESSAGE_SIZE = 10040,
    _SOCKET_ERROR_PROTOCOL_TYPE = 10041,
    _SOCKET_ERROR_PROTOCOL_OPTION = 10042,
    _SOCKET_ERROR_PROTOCOL_NOT_SUPPORTED = 10043,
    _SOCKET_ERROR_SOCKET_NOT_SUPPORTED = 10044,
    _SOCKET_ERROR_OPERATION_NOT_SUPPORTED = 10045,
    _SOCKET_ERROR_PROTOCOL_FAMILY_NOT_SUPPORTED = 10046,
    _SOCKET_ERROR_ADDRESS_FAMILY_NOT_SUPPORTED = 10047,
    _SOCKET_ERROR_ADDRESS_ALREADY_IN_USE = 10048,
    _SOCKET_ERROR_ADDRESS_NOT_AVAILABLE = 10049,
    _SOCKET_ERROR_NETWORK_DOWN = 10050,
    _SOCKET_ERROR_NETWORK_UNREACHABLE = 10051,
    _SOCKET_ERROR_NETWORK_RESET = 10052,
    _SOCKET_ERROR_CONNECTION_ABORTED = 10053,
    _SOCKET_ERROR_CONNECTION_RESET = 10054,
    _SOCKET_ERROR_NO_BUFFER_SPACE_AVAILABLE = 10055,
    _SOCKET_ERROR_IS_CONNECTED = 10056,
    _SOCKET_ERROR_NOT_CONNECTED = 10057,
    _SOCKET_ERROR_SHUTDOWN = 10058,
    _SOCKET_ERROR_TIMED_OUT = 10060,
    _SOCKET_ERROR_CONNECTION_REFUSED = 10061,
    _SOCKET_ERROR_HOST_DOWN = 10064,
    _SOCKET_ERROR_HOST_UNREACHABLE = 10065,
    _SOCKET_ERROR_OPERATION_ABORTED = 995,
    _SOCKET_ERROR_PROCESS_LIMIT = 10067,
    _SOCKET_ERROR_SYSTEM_NOT_READY = 10091,
    _SOCKET_ERROR_VERSION_NOT_SUPPORTED = 10092,
    _SOCKET_ERROR_NOT_INITIALIZED = 10093,
    _SOCKET_ERROR_DISCONNECTING = 10101,
    _SOCKET_ERROR_TYPE_NOT_FOUND = 10109,
    _SOCKET_ERROR_HOST_NOT_FOUND = 11001,
    _SOCKET_ERROR_TRY_AGAIN = 11002,
    _SOCKET_ERROR_NO_RECOVERY = 11003,
    _SOCKET_ERROR_NO_DATA = 11004
} _SocketError;

#ifndef _WIN32

/// <summary>
///     Maps a native error number to the corresponding <see cref="SocketError" /> value.
/// </summary>
i32 _FromNativeErrno(i32 e);

#endif

#endif
