#ifndef _SOCKETOPTIONNAME_H
#define _SOCKETOPTIONNAME_H

#include "_Types.h"

/// <summary>
///     Socket option names.
/// </summary>
typedef enum _SocketOptionName
{
    _SOCKET_OPTION_NAME_DEBUG = 1,
    _SOCKET_OPTION_NAME_ACCEPT_CONNECTION = 2,
    _SOCKET_OPTION_NAME_REUSE_ADDRESS = 4,
    _SOCKET_OPTION_NAME_KEEP_ALIVE = 8,
    _SOCKET_OPTION_NAME_DONT_ROUTE = 16,
    _SOCKET_OPTION_NAME_BROADCAST = 32,
    _SOCKET_OPTION_NAME_LINGER = 128,
    _SOCKET_OPTION_NAME_OUT_OF_BAND_INLINE = 256,
    _SOCKET_OPTION_NAME_SEND_BUFFER = 4097,
    _SOCKET_OPTION_NAME_RECEIVE_BUFFER = 4098,
    _SOCKET_OPTION_NAME_SEND_LOW_WATER = 4099,
    _SOCKET_OPTION_NAME_RECEIVE_LOW_WATER = 4100,
    _SOCKET_OPTION_NAME_SEND_TIMEOUT = 4101,
    _SOCKET_OPTION_NAME_RECEIVE_TIMEOUT = 4102,
    _SOCKET_OPTION_NAME_ERROR = 4103,
    _SOCKET_OPTION_NAME_TYPE = 4104,
    _SOCKET_OPTION_NAME_MAX_CONNECTIONS = 2147483647,
    _SOCKET_OPTION_NAME_IP_OPTIONS = 1,
    _SOCKET_OPTION_NAME_HEADER_INCLUDED = 2,
    _SOCKET_OPTION_NAME_TYPE_OF_SERVICE = 3,
    _SOCKET_OPTION_NAME_IP_TIME_TO_LIVE = 4,
    _SOCKET_OPTION_NAME_MULTICAST_INTERFACE = 9,
    _SOCKET_OPTION_NAME_MULTICAST_TIME_TO_LIVE = 10,
    _SOCKET_OPTION_NAME_MULTICAST_LOOPBACK = 11,
    _SOCKET_OPTION_NAME_ADD_MEMBERSHIP = 12,
    _SOCKET_OPTION_NAME_DROP_MEMBERSHIP = 13,
    _SOCKET_OPTION_NAME_DONT_FRAGMENT = 14,
    _SOCKET_OPTION_NAME_ADD_SOURCE_MEMBERSHIP = 15,
    _SOCKET_OPTION_NAME_DROP_SOURCE_MEMBERSHIP = 16,
    _SOCKET_OPTION_NAME_BLOCK_SOURCE = 17,
    _SOCKET_OPTION_NAME_UNBLOCK_SOURCE = 18,
    _SOCKET_OPTION_NAME_PACKET_INFORMATION = 19,
    _SOCKET_OPTION_NAME_NO_DELAY = 1,
    _SOCKET_OPTION_NAME_BSD_COMPAT = 14,
    _SOCKET_OPTION_NAME_EXPEDITED = 2,
    _SOCKET_OPTION_NAME_IPV6_HOP_LIMIT = 21,
    _SOCKET_OPTION_NAME_IPV6_PROTECTION_LEVEL = 23,
    _SOCKET_OPTION_NAME_IPV6_V6ONLY = 27
} _SocketOptionName;

#ifndef _WIN32

/// <summary>
///     Converts a managed <see cref="SocketOptionName" /> to the native unix socket option name value
///     for the specified level, handling level‑specific mappings.
/// </summary>
i32 _ToNativeSocketOptionName(i32 level, i32 name);

#endif

#endif
